### PR TITLE
Sketcher: simplify restore alignment function

### PR DESCRIPTION
**Pull request by 0penBrain**

### CODE REVIEW

**Comment by 0penBrain** [comment]
@AjinkyaDahale I have been curious about how exactly this may influence performance so just ran a test.
The bad news is that while my changes offer a "shorter" solution, it actually lowers the performance by a factor of 2. :( So it looks like this wasn't so good idea, and most probably you should revert and remove this commit from the FreeCAD PR.
The good news is that running this test allows to find a flaw in your previous commit. Actually `std::sort` shall be applied before using `std::unique` otherwise the latter just fails.
Here the testing code if you want to give it a go : 
```
#include <iostream>
#include <vector>
#include <set>
#include <algorithm>
#include <chrono>

#define TEST_DEPTH 100000

auto getEdgeGeoId = [](const int num) {
    return num*3;
};

auto noInternalGeo = [](const int num) {
    return (num%2 == 0);
};

int main(int argc, char **argv) {
    std::vector<int> SubNames;
    for (int i=0; i<100; i++) {
        SubNames.push_back((int)std::rand()/((RAND_MAX + 1u)/100));
    }

    //method 1
    auto start = std::chrono::steady_clock::now();
    for (int i=0; i<TEST_DEPTH; i++) {
        std::vector<int> SubGeoIds(SubNames.size());
        std::transform(SubNames.begin(), SubNames.end(), SubGeoIds.begin(), getEdgeGeoId);

        std::sort(SubGeoIds.begin(), SubGeoIds.end(), std::greater<int>());
        SubGeoIds.erase(std::unique(SubGeoIds.begin(), SubGeoIds.end()), SubGeoIds.end());
        SubGeoIds.erase(std::remove_if(SubGeoIds.begin(), SubGeoIds.end(), noInternalGeo), SubGeoIds.end());

        for (const auto& GeoId : SubGeoIds) {
            std::cout << GeoId << " ";
        }
        std::cout << "\n";
    }
    auto meth1_time = std::chrono::duration_cast<std::chrono::milliseconds>(std::chrono::steady_clock::now()-start);

    //method 2
    start = std::chrono::steady_clock::now();
    for (int i=0; i<TEST_DEPTH; i++) {
        std::set<int, std::greater<int>> SubGeoIds;
        std::transform(SubNames.begin(), SubNames.end(), std::inserter(SubGeoIds, SubGeoIds.begin()), getEdgeGeoId);
        for (const auto& GeoId : SubGeoIds) {
            if (noInternalGeo(GeoId))
                continue;
            std::cout << GeoId << " ";
        }
        std::cout << "\n";
    }
    auto meth2_time = std::chrono::duration_cast<std::chrono::milliseconds>(std::chrono::steady_clock::now()-start);
    std::cout << "Method 1 : " << meth1_time.count() << " // Method 2 : " << meth2_time.count();
}
```

**Comment by AjinkyaDahale** [comment]
> @AjinkyaDahale I have been curious about how exactly this may influence performance so just ran a test. 

Thanks for taking the time!

> The bad news is that while my changes offer a "shorter" solution, it actually lowers the performance by a factor of 2. :(

This is interesting. It would be interesting to know how this changes with the number of elements in the vector.

> The good news is that running this test allows to find a flaw in your previous commit. Actually `std::sort` shall be applied before using `std::unique` otherwise the latter just fails.

Reading the documentation again I should have known this:

> Eliminates all except the first element from every **consecutive** group of equivalent elements from the range [first, last) and returns a past-the-end iterator for the new logical end of the range.

That'll teach me not to lean on libraries too much.

**Comment by abdullahtahiriyo** [comment]
@AjinkyaDahale  @0penBrain 

I had a great time looking into optimizing a short list of integers. Although for the case is probably pointless, I appreciate the educative value (for other cases, with other times and other lengths).

I would like to comment on it, just for the sake of commenting (no changes are necessary, the code is good).

> std::vector<int> SubGeoIds(SubNames.size());

Instead of reserve() and push_back(). Actually (counterintuitively) yours is the right call for integers (which are cheap to initialise), the reason being that push_back needs to check that the capacity of the container is enough, so it has a penalty per insertion, which at a certain point outweights the cost of initialisation. With the right optimization, it is almost the same cost. But yet, in a performance competition we have a winner.

>         SubGeoIds.erase(std::unique(SubGeoIds.begin(), SubGeoIds.end()), SubGeoIds.end());
>        SubGeoIds.erase(std::remove_if(SubGeoIds.begin(), SubGeoIds.end(), noInternalGeo), SubGeoIds.end());

This could be written with a single erase (although I think it would be less readable, as the erase-remove is a well known easy to identify idiom). Because the GeoIds are sorted, it should also be possible to use a single std::remove_if for duplicates and noInternalGeo, which would nevertheless make the intention of the code less clear.

Another right call performance-wise is using std::vector and sorting it. Unless you need to have a set permanently sorted, generally using a set does not outweigh it performance-wise. Inserting in order in a set is rather expensive by comparison to a single sort. Where performance is not at issue, many programmers prefer using a set because the intention is better expressed. I do not have a strong opinion and happily live with either, unless it is going to be executed a lot of times and then performance reasons become relevant.

On a different topic, I wonder if we should simply remove the part of "if we did not expose anything, delete unused". At the time, there was some resistance to showing the poles, so this function enabled to "hide them". But I think this nowadays is overcome. The whole function could be removed from SketchObject and will be less code to maintain. The actual implementation would be better reflected for a command with the name "CmdSketcherRestoreInternalAlignmentGeometry" (who could expect the removal of unused internal alignment geometry from there). We can leave it for a discussion next year (if there is interest).

BTW, thanks for rewriting this function :)

**Comment by 0penBrain** [comment]
@abdullahtahiriyo Indeed looks like you had a great time. :) 
From an 'under hood' perspective, I guess that vector strength is that, as it guarantees data contiguous-ness, it can use pointer arithmetic for subsequent operations (sort, erase,...) while other types (set, list,...) have to use a data map table or so, and so needs to continuously dereference it. ;)

**Comment by AjinkyaDahale** [comment]
@abdullahtahiriyo I enjoyed reading your analysis as much as you evidently enjoyed performing it.

As for removing the function, I was imagining this would eventually be trivialized by putting these weights on their own layer (if/when the functionality is introduced) and hiding/showing it. Deleting internal geometries is quite an annoying process, and until we start supporting sketcher for tens of thousands of entities quite unnecessary.

**Pull request merged**
